feedly/config/routes.rb
Rails.application.routes.draw do

  
   root 'static_pages#home'
   get 'search' => 'static_pages#search'
   get    'signup'  => 'users#new'
   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   resources :users
   resources :statuses, only: [:create, :destroy] do
    resources :comments, only: [:create]
    member do
      post 'upvote'
      post 'downvote'
    end
   end

end

feedly/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
  validates :status_id, presence: true
  validates :body, presence: true, length: { maximum: 140 }

end

feedly/app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate  :picture_size

      # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end



end

feedly/app/models/user.rb
require 'elasticsearch/model'
class User < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :comments, dependent: :destroy
  has_many :statuses, dependent: :destroy
	attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	#validates unique and valid email address
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	#authenticates the user
	has_secure_password
	#validates password is of mimimum length and is non-blank
	validates :password, presence: true, length: { minimum: 6 }


	# Returns the hash digest of the given string.
    def User.digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database for use in persistent sessions.
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
      return false if remember_digest.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forgets a user.
    def forget
      update_attribute(:remember_digest, nil)
    end
    #Returns feeds of user with their status
    def feed
      Status.where("user_id = ?", id)
    end

    def self.search(query)
      
      __elasticsearch__.search(
      {
        query: {
        multi_match: {
          query: query,
          fields: ['name']
        }
      },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            name: {}
          }
        }
      }
    )
    end
end
User.import force: true

feedly/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

feedly/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [ :create]

  
  #creates comment
  def create
    @status = Status.find(params[:status_id])
    @comment = Comment.create(comment_params)
    @user=User.find_by(id: @status.user_id)
    if @comment.save
      redirect_to @user
    else
      redirect_to @user
    end
  end

 
  private
    def comment_params
      comment_hash = params.require(:comment).permit(:body,:status_id,:user_id)
    end
end

feedly/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  #let the user log in
  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in 
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

 #let the user log out.
  def destroy
  	log_out if logged_in?
    redirect_to root_url
  end
end

feedly/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  	if logged_in?
      @status  = current_user.statuses.build
      @feed_items = current_user.feed.paginate(page: params[:page], :per_page => 4)
    end
  end



 #search action used with elastic search
  def search
  	if params[:q].nil?
      @users = []
    else
      @users = User.search params[:q]
    end
  end

end

feedly/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

 #creates status
  def create
  	@status = current_user.statuses.build(status_params)
    @status.upvotes=0
    @status.downvotes=0
    if @status.save
      flash[:success] = "status created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
# it is used for deleting the status
  def destroy
  	@status.destroy
    flash[:success] = "Status deleted"
    redirect_to root_url

  end
#this is used for creating votes on status
  def upvote
    @status = Status.find(params[:id])
    @status.upvotes=@status.upvotes+1
    @status.save
    redirect_to root_url
  end

  def downvote
    @status = Status.find(params[:id])
    @status.downvotes=@status.downvotes+1
    @status.save
    redirect_to root_url
  end




  private

    def correct_user
      @status = current_user.statuses.find_by(id: params[:id])
      redirect_to root_url if @status.nil?
    end

    def status_params
      params.require(:status).permit(:content, :picture)
    end
end

feedly/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @statuses = @user.statuses.paginate(page: params[:page], :per_page => 4)
  end

  #redirects to the signup page
  def new
    @user = User.new
  end

  #creates a user, used in signup
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in @user
      flash.now[:success]= "Welcome to Feedly!"
      redirect_to @user
    else
      render 'new'
    end
  end

private

  def user_params
    params.require(:user).permit(:name,:email, :password, :password_confirmation)
  end
end

feedly/app/helpers/application_helper.rb
module ApplicationHelper
end

feedly/app/helpers/comments_helper.rb
module CommentsHelper
end

feedly/app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

feedly/app/helpers/statuses_helper.rb
module StatusesHelper
end

feedly/app/helpers/users_helper.rb
module UsersHelper
end

feedly/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Feedly %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

feedly/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

feedly/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="statuses">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

feedly/app/views/shared/_search_bar.html.erb
<%= form_for :search, url: search_path, method: :get do |f| %>
  <p>
    
    <%= text_field_tag :q, params[:q],class:"form-control",required:"true" %>
    <%= submit_tag "Go", name: nil,class:"btn btn-default"%>
  </p>
<% end %>

feedly/app/views/shared/_status_form.html.erb
<%= form_for(@status, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new status.", rows: "4",cols:"40",required:"true"  %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary",style:"width:340px" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#status_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

feedly/app/views/shared/_user_info.html.erb
<h1 style="margin-left:-140px"><%= current_user.name %></h1>

feedly/app/views/static_pages/home.html.erb
<% if logged_in? %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Feedly</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= render 'shared/search_bar' %></li>
        
        <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
      </ul>
     
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
  
</div>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="status_form">
        <%= render 'shared/status_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Status Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

<div class="center jumbotron">
  <h1>Welcome to Feedly</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

feedly/app/views/static_pages/search.html.erb
<ul>
  <h3><%= @users.count%> Result </h3><hr> 
  <% @users.each do |user| %>
    <li>
      <h3>

        <%= link_to user.try(:highlight).try(:name) ? user.highlight.name[0].html_safe : user.name,
          controller: "users",
          action: "show",
          id: user._id%>
      </h3>
    </li>
  <% end %>
</ul>

feedly/app/views/statuses/_status.html.erb
<li id="status-<%= status.id %>">
  <span class="user"><%= link_to status.user.name, status.user %></span>
    <span class="content">
      <%= status.content %>
      <%= image_tag status.picture.url if status.picture? %>
    </span>
  <span class="comment-all">
    <span class="timestamp">
      Posted <%= time_ago_in_words(status.created_at) %> ago.

      <%= button_to pluralize(status.upvotes,'Like'), upvote_status_path(status), method: :post %>
      <%= button_to pluralize(status.downvotes,'Dislike'), downvote_status_path(status), method: :post %>
      <%= link_to "Delete", status, method: :delete, data: { confirm: "You sure?" } %>
      <%= form_for([status, Comment.new]) do |f| %>
        <p>
          <%= f.label  "New Comment" %><br/>
          <%= f.text_area :body,required:"true"  %>
          <%= f.hidden_field :status_id, :value=>status.id %>
          <%= f.hidden_field :user_id, :value=>current_user.id %>
        </p>
        <p><%= f.submit "Add Comment"%></p>
      <% end %>
    </span>
    <div>
      <b>Comments</b>
      <% status.comments.each do |comment| %>
      <div> <%=comment.user.name%> - <%=comment.body %></div>
       <span class="timestamp">
        Posted <%= time_ago_in_words(comment.created_at) %> ago.
       </span>
      <% end %>
    </div>
  </span>
</li>

feedly/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <%= link_to "Already Have An Account?", login_path %>
    <% end %>
  </div>
  
</div>

feedly/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
      <h1>
        <%= @user.name %>
      </h1>
  </aside>

  <div class="container">
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= render 'shared/search_bar' %></li>
      <li><%= link_to "Home", root_url %></li>
      <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
    </ul>
  </nav>
</div>


  <div class="col-md-8">
      <h3>Statuses (<%= @user.statuses.count %>)</h3>
      <ol class="statuses">
        <%= render @statuses %>
      </ol>
      <%= will_paginate @statuses %>    
  </div>
</div>